#### Vectors and Sequences

In [17]:
seq(10);
seq(0, 1, length=9) # Create equally spaced sequences of 9 subintervals
seq(0, 10, by=1)
rep(2,3)
rep(-1, 4)
rep(1:3, 2)
rep('A', 4) 
c(rep('A',3), rep('B',3)) 
rep(c('A', 'B'), 3) 

[1]  1  2  3  4  5  6  7  8  9 10

[1] 0.000 0.125 0.250 0.375 0.500 0.625 0.750 0.875 1.000

[1]  0  1  2  3  4  5  6  7  8  9 10

[1] 2 2 2

[1] -1 -1 -1 -1

[1] 1 2 3 1 2 3

[1] "A" "A" "A" "A"

[1] "A" "A" "A" "B" "B" "B"

[1] "A" "B" "A" "B" "A" "B"

In [1]:
c(seq(3, 9, by=2))
c(rep(2,2), rep(3,3), rep(4,4))
rep(c('High', 'Medium', 'Low'), 2)
rep(c(1,2,3), each=2, 5)  # each=2 repeats each element of vector twice

[1] 3 5 7 9

[1] 2 2 3 3 3 4 4 4 4

[1] "High"   "Medium" "Low"    "High"   "Medium" "Low"

[1] 1 1 2 2 3 3 1 1 2 2 3 3 1 1 2 2 3 3 1 1 2 2 3 3 1 1 2 2 3 3

In [30]:
poker_winnings <- c(140, -50, 20, -120, 240)
roulette_winnings <- c(-24, -50, 100, -350, 10)
days <- c('Mon', 'Tue', 'Wed', 'Thu', 'Fri')
names(poker_winnings) <- days
names(roulette_winnings) <- days
names(which(poker_winnings > 0))
daily_winnings <- poker_winnings + roulette_winnings; daily_winnings
names(which(daily_winnings > 0))
sum(poker_winnings)
sum(roulette_winnings)

[1] "Mon" "Wed" "Fri"

Mon  Tue  Wed  Thu  Fri 
 116 -100  120 -470  250

[1] "Mon" "Wed" "Fri"

[1] 230

[1] -314

#### Matrices

In [5]:
matrix_4x2 <- matrix(1:8, byrow=FALSE, nrow=4); matrix_4x2
matrix_2x4 <- matrix(c(1,2,3,4,11,12,13,14), byrow=TRUE, nrow=2); matrix_2x4
matrix_4x2 %*% matrix_2x4  # %*% denotes matrix multiplication, * denotes component-wise multiplication
matrix_2x4 %*% matrix_4x2
matrix_2x2 <- matrix_4x2[1:2,]; matrix_2x2  # Selects first 2 rows of matrix_4x2
matrix_4x2[,2] # Selects 2nd column of matrix_4x2
solve(matrix_2x2)  # Finds the inverse of matrix_2x2
diag(3)  # Creates a 3x3 identity matrix
diag(c(2, 3, 5))  # Creates a diagonal matrix of given vector

[,1] [,2]
[1,] 1    5   
[2,] 2    6   
[3,] 3    7   
[4,] 4    8

[,1] [,2] [,3] [,4]
[1,]  1    2    3    4  
[2,] 11   12   13   14

[,1] [,2] [,3] [,4]
[1,] 56    62   68   74 
[2,] 68    76   84   92 
[3,] 80    90  100  110 
[4,] 92   104  116  128

[,1] [,2]
[1,]  30   70 
[2,] 130  330

[,1] [,2]
[1,] 1    5   
[2,] 2    6

[1] 5 6 7 8

[,1] [,2] 
[1,] -1.5  1.25
[2,]  0.5 -0.25

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    1    0   
[3,] 0    0    1

[,1] [,2] [,3]
[1,] 2    0    0   
[2,] 0    3    0   
[3,] 0    0    5

In [26]:
apple <- c(350, 150) 
orange <- c(400, 230) 
watermelon <- c(180, 90) 
fruit_matrix <- matrix(c(apple, orange, watermelon), byrow=TRUE, nrow=3); fruit_matrix
rownames(fruit_matrix) <- c('Apple', 'Orange', 'Watermelon')
colnames(fruit_matrix) <- c('Weekday', 'Weekend')
rowSums(fruit_matrix)
colSums(fruit_matrix)
fruit_matrix <- cbind(fruit_matrix, rowSums(fruit_matrix))
total_sale <- sum(fruit_matrix[,3] * c(1, 1.5, 4)); total_sale

[,1] [,2]
[1,] 350  150 
[2,] 400  230 
[3,] 180   90

Apple     Orange Watermelon 
       500        630        270

Weekday Weekend 
    930     470

[1] 2525